name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Enable Required APIs
        run: |
          gcloud services enable run.googleapis.com
          gcloud services enable containerregistry.googleapis.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:latest .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy nextjs-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 3000
